# For a description of these parameters, please visit the theme wiki.
# https://github.com/pacollins/hugo-future-imperfect-slim/wiki/config.toml
baseurl                 = "/"
DefaultContentLanguage  = "en"
title                   = "David's Blog"
theme                   = "future"
paginate                = 6
disqusShortname         = "davidh83110"
googleAnalytics         = ""
pluralizeListTitles     = false
disableLanguages        = ["fr", "pt", "zh-CN", "es", "de", "ja", "pl"]
publishDir              = "docs"


[taxonomies]
  category = "categories"
  series = "series"



[params]
  enableCDN             = false
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = "github"
  highlightjsLang       = ["html", "css", "js", "toml"]
  viewMorePostsLink     = "/blog/"
  readingTime           = false
  socialShare           = ["facebook", "linkedin", "email"]

  [params.meta]
    description         = ""
    author              = "David"
    favicon             = true
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [params.header]
    navbarTitle         = "David's Blog"
    dynamicTitles       = true
    searchMenu          = true
    shareMenu           = true
    languageMenu        = true

  [params.intro]
    header                = "David Hsu"
    paragraph             = "DevOps Engineering / AWS / Cloud Native"
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false

    [params.intro.pic]
      src                 = "img/main/avator.jpg"
      shape               = "circle"
      width               = "165px"
      alt                 = ""

  [params.sidebar]
    about               = "This theme was developed for Hugo static site generator."
    postAmount          = 5
    categories          = true
    categoriesByCount   = true

  [params.footer]
    rssFooter           = true
    socialFooter        = true

  [params.staticman]
    enabled             = false
    api                 = ""  # No Trailing Slash
    gitProvider         = ""
    username            = ""
    repo                = ""
    branch              = ""

    [params.staticman.recaptcha]
      siteKey           = ""
      encryptedKey      = ""

[menu]

  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = "/"
    pre               = "<i class='fa fa-bars'></i>"
    weight            = 1

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "/about/"
    pre               = "<i class='far fa-bookmark'></i>"
    weight            = 2

  [[menu.main]]
    name              = "Blog"
    identifier        = "blog"
    url               = "/blog/"
    pre               = "<i class='far fa-newspaper'></i>"
    weight            = 3

  [[menu.main]]
    name              = "Categories"
    identifier        = "categories"
    url               = "/categories/"
    pre               = "<i class='fas fa-sitemap'></i>"
    weight            = 5

  # [[menu.main]]
  #   name              = "Contact"
  #   identifier        = "contact"
  #   url               = "/contact/"
  #   pre               = "<i class='far fa-envelope'></i>"
  #   weight            = 6

  [[menu.main]]
    name              = "Archived"
    identifier        = "archived"
    url               = "/archived/"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 7


[Languages]

  [Languages.en]
    LanguageCode        = "en"
    LanguageName        = "English"
    weight              = 1

  [Languages.zh-TW]
    LanguageCode        = "zh-TW"
    LanguageName        = "中文"
    weight              = 8


[social]
  # Coding Communities
  github                = "davidh83110"
#  gitlab                = ""
  stackoverflow         = "12397001" # User Number
#  bitbucket             = ""
#  jsfiddle              = ""
#  codepen               = ""
  # Visual Art Communities
#  deviantart            = ""
#  flickr                = "example"
#  behance               = ""
#  dribbble              = ""
  # Publishing Communities
#  wordpress             = ""
  # medium                = ""
  # Professional/Business Oriented Communities
  linkedin              = "david-hsu-b1136112b"
#  linkedin_company      = "examplebusiness"
#  foursquare            = ""
#  xing                  = ""
  slideshare            = "DavidHsu64"
  # Social Networks
  facebook              = "ben12567"
#  googleplus            = ""
#  reddit                = "example"
#  quora                 = ""
#  youtube               = ""
#  vimeo                 = ""
#  whatsapp              = "" # WhatsApp Number
    # WeChat and QQ need testing.
#    wechat              = ""
#    qq                  = "" # User ID Number
  instagram             = "davidh.110"
#  tumblr                = ""
#  twitter               = "example"
#  strava                = ""
#  skype                 = ""
#  snapchat              = ""
#  pinterest             = "example"
  # telegram              = "davidh83110"
#  vine                  = ""
#  googlescholar         = ""
#  orcid                 = ""
#  researchgate          = "example"
#  keybase               = "example"
#  mastodon              = "example.com/@example"
  # Email
  email                 = "davidh83110@gmail.com"
